import { IEditableCourse } from "./IEditableCourse";
import { IStudent } from "./IStudent";
import { ITimetableExportConfig } from "./ITimetableExportConfig";


export interface ITimetable {
    // id Should be auto-generated by uuid
    id?: string;

    timetableName: string;
    createdDate: Date;
    lastModifiedDate: Date;
    createdBy: IStudent;
    description: string;

    exportConfig: ITimetableExportConfig;
    editableCourses: IEditableCourse[];
}