
import { DayOfWeek } from "../enums/DayOfWeek";


export interface ITime {
    // id Should be auto-generated by uuid
    id?: string;
    
    beginTime: number;
    endTime: number;
    dayOfWeek: DayOfWeek;
    venue: string;
}