
import { DayOfWeek } from "../../enums/DayOfWeek";


export interface ITime {
    // id Should be auto-generated by uuid, or provided by the API
    id: string;
    
    beginTime: number;
    endTime: number;
    dayOfWeek: DayOfWeek;
    venue: string;
}