import { IEditableCourse } from "./IEditableCourse";
import { IStudent } from "./IStudent";
import { ITimetableExportConfig } from "./ITimetableExportConfig";


export interface ITimetable {
    // id Should be auto-generated by uuid
    id: string;

    timetableName: string;
    createdDate: string;
    lastModifiedDate: string;
    createdBy: IStudent;
    description: string;

    exportConfig: ITimetableExportConfig;
    editableCourses: { [id: string]: IEditableCourse };
}